### ISSUE TITLE
mlbench worker pods not created

### ISSUE THREAD

**Issue by Pl4tiNuM** [mlbench/mlbench-helm#11]
Hello,

I succesfully deployed mlbench using heml, but I see in my pods that no worker instances have been spawned. In addition, inside the templates folder there is not yaml for worker deployment. 

Is this something missing? How to fix this? 

Thanks in advance

**Comment by Panaetius** [comment]
Please excuse the late reply.

The mlbench master/dashboard will provision workers as needed, so the dummy mlbench/mlbench_worker is not needed anymore.

**Comment by ehoelzl** [comment]
Closing this as it is not a problem anymore
