### ISSUE TITLE
Deployment on minikube requires kubernetes 1.15

### ISSUE THREAD

**Issue by cgrigis** [mlbench/mlbench-helm#13]
[opening the issue here but I am not sure it is the right place]

While following the documentation to install using minikube (which by default installs kubernetes 1.18), I get this error at the `helm upgrade` step:
```
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
```

Changing the chart as follows:
```diff
diff --git a/templates/master-deployment.yaml b/templates/master-deployment.yaml
index 396e25b..4cd5244 100644
--- a/templates/master-deployment.yaml
+++ b/templates/master-deployment.yaml
@@ -1,4 +1,4 @@
-apiVersion: apps/v1beta2
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: {{ template "mlbench.master.fullname" . }}
```
works, but then the dashboard fails to start a run:
```
Run failed
Traceback (most recent call last):
(...)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 17 Apr 2020 19:08:54 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```

I assume the dashboard is calling the API using `apps/v1beta2`?

To make it work, I had to force minikube to install kubernetes 1.15:
```
$ minikube start --kubernetes-version=1.15.0
```
What version of kubernetes does the deployment on Google Cloud use?

**Comment by cgrigis** [comment]
I realize now that I was for some reason looking at the _stable_ doc, as opposed to the _latest_ one, and that this point is now addressed, indicating to modify `/etc/kubernetes/manifest/kube-apiserver.yaml`. I have however not found this file in my `minikube` installation.

**Comment by mmilenkoski** [comment]
I also could not find the file in my installation. I fixed this issue by starting minikube with the following command:

`minikube start --extra-config=apiserver.runtime-config=apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true` 

@ehoelzl should we add this alternative to the docs?
