### ISSUE TITLE
Migrate to Kubernetes API v1

### ISSUE THREAD

**Issue by mmilenkoski** [mlbench/mlbench-helm#15]
Kubernetes 1.16 deprecated some of the APIs that we use:

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Most importantly, it deprecated `Deployment` in `apps/v1beta2` that we use in `templates/master-deployment.yaml`. It also deprecated some of the features used in the weave and Nvidia templates.

Simple migration of the templates is not enough because we are using some of the deprecated APIs in the dashboard.

So far, we have been mitigating the issue by modifying the runtime config with:

`apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true`

However, modifying the runtime-config of the api-server is not always doable. For example, when using kops with AWS, it is not possible to automate it, so we would need to require a manual edit of the config by users. 

I believe we should address this. I can pick it up myself, but I wanted to check first whether we should do it and whether something is preventing us from migrating.

**Comment by ehoelzl** [comment]
Update on this ? @mmilenkoski
