### ISSUE TITLE
Can not configure NVIDIA on AWS

### ISSUE THREAD

**Issue by mmilenkoski** [mlbench/mlbench-helm#17]
To setup GPU cluster on AWS we need to set the machine type to a gpu-enable one like `p2.xlarge` and increase the number of gpus in `aws_setup.sh`. 

As per the instructions [here](https://eksctl.io/usage/gpu-support/) and [here](https://github.com/NVIDIA/k8s-device-plugin), `aws_setup.sh` calls:

`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta6/nvidia-device-plugin.yml`

However, `helm install` later tries to install the nvidia-plugin provided by us in `templates/nvidia-device-plugin.yaml` which fails because it already exists. 

Not installing the plugin in `aws_setup.sh` and using the one provided by us causes the runs to fail. I suspect that this I because our template is outdated. I don't know what is the right approach to deal with this. 

This issue might be related to #15 if the cause is the stale kubernetes version.

**Comment by Panaetius** [comment]
The nvidia-device--plugin is needed on gcloud (and the url is from their docs), we could make installing it optional with a flag in the values.yaml

**Comment by ehoelzl** [comment]
@mmilenkoski This has been solved right ? Can we close it ?
