### ISSUE TITLE
Use of GCloud script

### ISSUE THREAD

**Issue by ehoelzl** [mlbench/mlbench-helm#19]
In the blog post https://mlbench.github.io/2018/09/10/tutorial/, we mention the use of `google_cloud_setup.sh` for deploying clusters. However, this method is not used anymore, as we have switched to the CLI. 

Should we keep those scripts ? or maybe put it in a `_old_scripts` folder as to avoid confusion ?

Also, is the AWS script also necessary ? @mmilenkoski

**Comment by martinjaggi** [comment]
seems best to delete then and update switch to CLI

**Comment by ehoelzl** [comment]
@mmilenkoski Does AWS work with CLI ?

**Comment by mmilenkoski** [comment]
yes, it works. There is an issue with creating GPU clusters but it is not specific to the CLI, the same problem happens with the script as well, so we can remove it.
