### ISSUE TITLE
Add Google Cloud setup script

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-helm#2]
Add a bash script to automatically setup a cluster in google cloud and install the mlbench helm chart

**Comment by LucianaMarques** [comment]
This would be a nice thing to put on the docs! What's the current state?

**Comment by Panaetius** [comment]
I've added https://github.com/mlbench/mlbench-helm/blob/develop/google_cloud_setup.sh but haven't had a chance to thoroughly test it, so it's pretty much a work in progress. But it's based on a script that works well and testing it (with our new benchmark images) is on my todo list for tomorrow.

**Comment by LucianaMarques** [comment]
We could make some tests in a VM, or maybe use some automated tests in case you haven't done it already.

How did you test it? 

And what's the definition of "done" to your WIP? Is it working on an specific OS or all of them, etc?

**Comment by Panaetius** [comment]
I tested it with all images on GKE by running the script on my local machine (Arch Linux) and it worked as expected. 

We used to have tests with kubeadm-dind-cluster to run a cluster locally, but it got quite complicated and tests took too long, plus DIND does not support all features. so in the end we removed those automated tests.
