### ISSUE TITLE
Add Amazon Cloud setup script

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-helm#3]
Add a bash script to automatically setup a cluster and install mlbench in the amazon cloud

**Comment by LucianaMarques** [comment]
Hey @Panaetius just out of curiosity, what's the state of this issue?

**Comment by Panaetius** [comment]
It's currently on hold, as we're still in the process of trying to get some AWS credits to test on AWS.

**Comment by ehoelzl** [comment]
Closing this issue, as it has been resolved.
