### ISSUE TITLE
Add DIND Setup Script

### ISSUE THREAD

**Issue by Panaetius** [mlbench/mlbench-helm#4]
Add a script akin to the google cloud one to setup a local kubeadm-dind-cluster deployment.

**Comment by LucianaMarques** [comment]
Hey @Panaetius, what is the state of this issue? Is someone already working on it? I'd like to give it a look is available!

**Comment by Panaetius** [comment]
This is still available, so feel free to work on it :)

**Comment by Panaetius** [comment]
Keep in mind that `CNI_PLUGIN` environment variable has to be set to `weave` for communication to work correctly.

**Comment by ehoelzl** [comment]
Should we drop this ? As we now have KIND script
